### PR TITLE
Update README.md to match 3.0.4

### PR DESCRIPTION
**Pull request by AlexITC**
The version 3.0.4 contains several api breaking changes,
this updates some examples.

### CODE REVIEW

**Comment by AlexITC** [comment]
please, squash my commits before merging.

**Comment by vogelito** [comment]
Vic,

Please see email below and remember this is a public repo. We should take care of keeping docs up to date when making changes.

Let's try and address this pull request today, hopefully we'll see more development :)

Best,
Daniel

iPhoned

**Comment by nvcruzhe** [comment]
Updates have been done, and a new release has been launched. Release available for mvn and gradle at: https://jitpack.io/#bitsoex/bitso-java.

**Comment by nvcruzhe** [comment]
Changes have been done in the new release 3.0.5. Release available at https://jitpack.io/#bitsoex/bitso-java

**Pull request closed without merging**
